// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Blog documents */
type BlogDocumentData = Record<string, never>;
/**
 * Blog document from Prismic
 *
 * - **API ID**: `Blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "Blog", Lang>;
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: Footer.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Slice for *Footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice = FooterWidgetSlice;
/**
 * Footer document from Prismic
 *
 * - **API ID**: `Footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "Footer", Lang>;
/** Content for Header documents */
interface HeaderDocumentData {
    /**
     * Logo field in *Header*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header.Logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    Logo: prismicT.ImageField<never>;
    /**
     * Site Name field in *Header*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: header.SiteName
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    SiteName: prismicT.RichTextField;
    /**
     * Navigation field in *Header*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: header.Navigation[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    Navigation: prismicT.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;
    /**
     * Button Text field in *Header*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: header.ButtonText
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    ButtonText: prismicT.KeyTextField;
    /**
     * Button Link field in *Header*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: header.ButtonLink
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    ButtonLink: prismicT.LinkField;
}
/**
 * Item in Header → Navigation
 *
 */
export interface HeaderDocumentDataNavigationItem {
    /**
     * Menu Name field in *Header → Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: header.Navigation[].MenuName
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    MenuName: prismicT.KeyTextField;
    /**
     * Menu Link field in *Header → Navigation*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: header.Navigation[].MenuLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    MenuLink: prismicT.LinkField;
}
/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HeaderDocumentData>, "header", Lang>;
/** Content for Page documents */
type PageDocumentData = Record<string, never>;
/**
 * Page document from Prismic
 *
 * - **API ID**: `Page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "Page", Lang>;
export type AllDocumentTypes = BlogDocument | FooterDocument | HeaderDocument | PageDocument;
/**
 * Primary content in ContactUs → Primary
 *
 */
interface ContactUsSliceDefaultPrimary {
    /**
     * Button Text field in *ContactUs → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_us.primary.ButtonText
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    ButtonText: prismicT.KeyTextField;
    /**
     * Button Link field in *ContactUs → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_us.primary.ButtonLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    ButtonLink: prismicT.LinkField;
    /**
     * Button Type field in *ContactUs → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_us.primary.ButtonType
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    ButtonType: prismicT.SelectField<"primary" | "secondary">;
}
/**
 * Item in ContactUs → Items
 *
 */
export interface ContactUsSliceDefaultItem {
    /**
     * Social Media Name field in *ContactUs → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_us.items[].SocialMediaName
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    SocialMediaName: prismicT.KeyTextField;
    /**
     * Social Media Link field in *ContactUs → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_us.items[].SocialMediaLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    SocialMediaLink: prismicT.LinkField;
    /**
     * Social Media Icon field in *ContactUs → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_us.items[].SocialMediaIcon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    SocialMediaIcon: prismicT.ImageField<never>;
}
/**
 * Default variation for ContactUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ContactUs`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactUsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ContactUsSliceDefaultPrimary>, Simplify<ContactUsSliceDefaultItem>>;
/**
 * Slice variation for *ContactUs*
 *
 */
type ContactUsSliceVariation = ContactUsSliceDefault;
/**
 * ContactUs Shared Slice
 *
 * - **API ID**: `contact_us`
 * - **Description**: `ContactUs`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactUsSlice = prismicT.SharedSlice<"contact_us", ContactUsSliceVariation>;
/**
 * Primary content in FooterWidget → Primary
 *
 */
interface FooterWidgetSliceDefaultPrimary {
    /**
     * Widget Title field in *FooterWidget → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_widget.primary.WidgetTitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    WidgetTitle: prismicT.RichTextField;
}
/**
 * Item in FooterWidget → Items
 *
 */
export interface FooterWidgetSliceDefaultItem {
    /**
     * Menu Text field in *FooterWidget → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_widget.items[].MenuText
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    MenuText: prismicT.KeyTextField;
    /**
     * Menu Link field in *FooterWidget → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_widget.items[].MenuLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    MenuLink: prismicT.LinkField;
}
/**
 * Default variation for FooterWidget Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FooterWidget`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterWidgetSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterWidgetSliceDefaultPrimary>, Simplify<FooterWidgetSliceDefaultItem>>;
/**
 * Slice variation for *FooterWidget*
 *
 */
type FooterWidgetSliceVariation = FooterWidgetSliceDefault;
/**
 * FooterWidget Shared Slice
 *
 * - **API ID**: `footer_widget`
 * - **Description**: `FooterWidget`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterWidgetSlice = prismicT.SharedSlice<"footer_widget", FooterWidgetSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BlogDocumentData, BlogDocument, FooterDocumentData, FooterDocumentDataSlicesSlice, FooterDocument, HeaderDocumentData, HeaderDocumentDataNavigationItem, HeaderDocument, PageDocumentData, PageDocument, AllDocumentTypes, ContactUsSliceDefaultPrimary, ContactUsSliceDefaultItem, ContactUsSliceDefault, ContactUsSliceVariation, ContactUsSlice, FooterWidgetSliceDefaultPrimary, FooterWidgetSliceDefaultItem, FooterWidgetSliceDefault, FooterWidgetSliceVariation, FooterWidgetSlice };
    }
}
