// Code generated by Slice Machine. DO NOT EDIT.

import ContactUs from './ContactUs';
import FooterWidget from './FooterWidget';

export {
	ContactUs,
	FooterWidget,
};

export const components = {
	contact_us: ContactUs,
	footer_widget: FooterWidget,
};
